import { Edge, Node } from "@xyflow/react";
import { TableNodeData } from "@/lib/mockData";

export interface DatabaseSchemaResult {
  nodes: Node<TableNodeData>[];
  edges: Edge[];
  tablesCount: number;
  fksCount: number;
}

// Engine-specific schema table definitions (comprehensive full domain models for every database engine)
export const ENGINE_SCHEMAS: Record<
  string,
  { tables: TableNodeData[]; fks: { from: string; to: string; label: string }[] }
> = {
  PostgreSQL: {
    tables: [
      {
        tableName: "users",
        schema: "public",
        rowCount: 14250,
        description: "User identity, credentials, and access tier roles",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "email", type: "varchar(255)", isNullable: false },
          { name: "username", type: "varchar(50)", isNullable: false },
          { name: "role", type: "varchar(20)", isNullable: false },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "profiles",
        schema: "public",
        rowCount: 14250,
        description: "User profile metadata, display preferences, and avatars",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "user_id", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "display_name", type: "varchar(100)", isNullable: false },
          { name: "avatar_url", type: "text", isNullable: true },
          { name: "bio", type: "text", isNullable: true },
          { name: "timezone", type: "varchar(50)", isNullable: false },
          { name: "updated_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "organizations",
        schema: "public",
        rowCount: 320,
        description: "Multi-tenant workspace organizations and billing tiers",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "name", type: "varchar(100)", isNullable: false },
          { name: "slug", type: "varchar(50)", isNullable: false },
          { name: "plan", type: "varchar(25)", isNullable: false },
          { name: "owner_id", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "organization_members",
        schema: "public",
        rowCount: 1840,
        description: "Team membership roles within organizations",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "org_id", type: "uuid", isForeignKey: true, foreignKeyRef: "organizations.id" },
          { name: "user_id", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "role", type: "varchar(20)", isNullable: false },
          { name: "joined_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "projects",
        schema: "public",
        rowCount: 780,
        description: "Active engineering projects, applications, and microservices",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "org_id", type: "uuid", isForeignKey: true, foreignKeyRef: "organizations.id" },
          { name: "name", type: "varchar(100)", isNullable: false },
          { name: "description", type: "text", isNullable: true },
          { name: "status", type: "varchar(20)", isNullable: false },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "environments",
        schema: "public",
        rowCount: 2340,
        description: "Staging, preview, and production deployment environments",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "project_id", type: "uuid", isForeignKey: true, foreignKeyRef: "projects.id" },
          { name: "name", type: "varchar(50)", isNullable: false },
          { name: "cluster_region", type: "varchar(30)", isNullable: false },
          { name: "is_production", type: "boolean", isNullable: false },
        ],
      },
      {
        tableName: "deployments",
        schema: "public",
        rowCount: 19800,
        description: "Immutable build releases and deployment logs",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "environment_id", type: "uuid", isForeignKey: true, foreignKeyRef: "environments.id" },
          { name: "commit_hash", type: "varchar(40)", isNullable: false },
          { name: "status", type: "varchar(20)", isNullable: false },
          { name: "deployed_by", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "deployed_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "accounts",
        schema: "public",
        rowCount: 14250,
        description: "Billing accounts, balances, and payment profiles",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "user_id", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "org_id", type: "uuid", isForeignKey: true, foreignKeyRef: "organizations.id" },
          { name: "balance_cents", type: "int8", isNullable: false },
          { name: "currency", type: "varchar(3)", isNullable: false },
        ],
      },
      {
        tableName: "subscriptions",
        schema: "public",
        rowCount: 1200,
        description: "Active SaaS recurring subscriptions and entitlements",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "account_id", type: "uuid", isForeignKey: true, foreignKeyRef: "accounts.id" },
          { name: "plan_id", type: "varchar(50)", isNullable: false },
          { name: "status", type: "varchar(20)", isNullable: false },
          { name: "current_period_end", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "invoices",
        schema: "public",
        rowCount: 7400,
        description: "Itemized recurring billing invoices and receipts",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "subscription_id", type: "uuid", isForeignKey: true, foreignKeyRef: "subscriptions.id" },
          { name: "amount_cents", type: "int8", isNullable: false },
          { name: "status", type: "varchar(20)", isNullable: false },
          { name: "issued_at", type: "timestamptz", isNullable: false },
          { name: "paid_at", type: "timestamptz", isNullable: true },
        ],
      },
      {
        tableName: "api_keys",
        schema: "public",
        rowCount: 850,
        description: "Service API tokens with scoped permission grants",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "org_id", type: "uuid", isForeignKey: true, foreignKeyRef: "organizations.id" },
          { name: "key_prefix", type: "varchar(12)", isNullable: false },
          { name: "hash", type: "varchar(64)", isNullable: false },
          { name: "expires_at", type: "timestamptz", isNullable: true },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "webhooks",
        schema: "public",
        rowCount: 420,
        description: "Real-time webhook callback subscriptions and retry policies",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "project_id", type: "uuid", isForeignKey: true, foreignKeyRef: "projects.id" },
          { name: "target_url", type: "text", isNullable: false },
          { name: "secret_token", type: "varchar(64)", isNullable: false },
          { name: "is_active", type: "boolean", isNullable: false },
        ],
      },
      {
        tableName: "audit_logs",
        schema: "public",
        rowCount: 89400,
        description: "Immutable compliance audit events and access trail",
        columns: [
          { name: "id", type: "bigserial", isPrimaryKey: true },
          { name: "user_id", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "org_id", type: "uuid", isForeignKey: true, foreignKeyRef: "organizations.id" },
          { name: "action", type: "varchar(100)", isNullable: false },
          { name: "ip_address", type: "inet", isNullable: false },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "system_metrics",
        schema: "public",
        rowCount: 450000,
        description: "Infrastructure latency, CPU, and connection pool metrics",
        columns: [
          { name: "id", type: "bigserial", isPrimaryKey: true },
          { name: "project_id", type: "uuid", isForeignKey: true, foreignKeyRef: "projects.id" },
          { name: "metric_name", type: "varchar(50)", isNullable: false },
          { name: "value", type: "float8", isNullable: false },
          { name: "recorded_at", type: "timestamptz", isNullable: false },
        ],
      },
    ],
    fks: [
      { from: "profiles", to: "users", label: "user_id → id" },
      { from: "organizations", to: "users", label: "owner_id → id" },
      { from: "organization_members", to: "organizations", label: "org_id → id" },
      { from: "organization_members", to: "users", label: "user_id → id" },
      { from: "projects", to: "organizations", label: "org_id → id" },
      { from: "environments", to: "projects", label: "project_id → id" },
      { from: "deployments", to: "environments", label: "environment_id → id" },
      { from: "deployments", to: "users", label: "deployed_by → id" },
      { from: "accounts", to: "users", label: "user_id → id" },
      { from: "accounts", to: "organizations", label: "org_id → id" },
      { from: "subscriptions", to: "accounts", label: "account_id → id" },
      { from: "invoices", to: "subscriptions", label: "subscription_id → id" },
      { from: "api_keys", to: "organizations", label: "org_id → id" },
      { from: "webhooks", to: "projects", label: "project_id → id" },
      { from: "audit_logs", to: "users", label: "user_id → id" },
      { from: "audit_logs", to: "organizations", label: "org_id → id" },
      { from: "system_metrics", to: "projects", label: "project_id → id" },
    ],
  },

  Supabase: {
    tables: [
      {
        tableName: "users",
        schema: "public",
        rowCount: 14250,
        description: "Supabase Auth linked profiles & identity records",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "username", type: "varchar(50)", isNullable: false },
          { name: "email", type: "varchar(255)", isNullable: false },
          { name: "role", type: "varchar(20)", isNullable: false },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "profiles",
        schema: "public",
        rowCount: 14250,
        description: "Public user profile details and avatars",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "user_id", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "full_name", type: "varchar(100)", isNullable: false },
          { name: "avatar_url", type: "text", isNullable: true },
          { name: "updated_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "teams",
        schema: "public",
        rowCount: 450,
        description: "Collaborative developer teams and shared access groups",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "name", type: "varchar(100)", isNullable: false },
          { name: "slug", type: "varchar(50)", isNullable: false },
          { name: "created_by", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "team_members",
        schema: "public",
        rowCount: 2100,
        description: "Team membership associations and permissions",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "team_id", type: "uuid", isForeignKey: true, foreignKeyRef: "teams.id" },
          { name: "user_id", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "role", type: "varchar(20)", isNullable: false },
        ],
      },
      {
        tableName: "quizzes",
        schema: "public",
        rowCount: 120,
        description: "Evaluations, interactive challenges, and skill tests",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "created_by", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "team_id", type: "uuid", isForeignKey: true, foreignKeyRef: "teams.id" },
          { name: "title", type: "varchar(150)", isNullable: false },
          { name: "category", type: "varchar(50)", isNullable: false },
          { name: "is_published", type: "boolean", isNullable: false },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "problems",
        schema: "public",
        rowCount: 540,
        description: "Algorithmic challenges and unit test suites",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "quiz_id", type: "uuid", isForeignKey: true, foreignKeyRef: "quizzes.id" },
          { name: "title", type: "varchar(150)", isNullable: false },
          { name: "difficulty", type: "varchar(16)", isNullable: false },
          { name: "points", type: "int4", isNullable: false },
        ],
      },
      {
        tableName: "quiz_problems",
        schema: "public",
        rowCount: 1200,
        description: "Many-to-many junction connecting problems to quizzes",
        columns: [
          { name: "quiz_id", type: "uuid", isPrimaryKey: true, isForeignKey: true, foreignKeyRef: "quizzes.id" },
          { name: "problem_id", type: "uuid", isPrimaryKey: true, isForeignKey: true, foreignKeyRef: "problems.id" },
          { name: "order_index", type: "int4", isNullable: false },
        ],
      },
      {
        tableName: "submissions",
        schema: "public",
        rowCount: 68900,
        description: "Code evaluation executions and score history",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "user_id", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "problem_id", type: "uuid", isForeignKey: true, foreignKeyRef: "problems.id" },
          { name: "status", type: "varchar(24)", isNullable: false },
          { name: "execution_time_ms", type: "int4", isNullable: false },
          { name: "score_awarded", type: "int4", isNullable: false },
          { name: "submitted_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "storage_buckets",
        schema: "storage",
        rowCount: 12,
        description: "Supabase Object Storage media buckets",
        columns: [
          { name: "id", type: "varchar(64)", isPrimaryKey: true },
          { name: "name", type: "varchar(64)", isNullable: false },
          { name: "owner", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "is_public", type: "boolean", isNullable: false },
          { name: "file_size_limit", type: "bigint", isNullable: true },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "storage_objects",
        schema: "storage",
        rowCount: 45000,
        description: "Supabase storage binary assets and metadata",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "bucket_id", type: "varchar(64)", isForeignKey: true, foreignKeyRef: "storage_buckets.id" },
          { name: "name", type: "text", isNullable: false },
          { name: "owner", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "metadata", type: "jsonb", isNullable: true },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "auth_sessions",
        schema: "auth",
        rowCount: 12400,
        description: "Active user refresh tokens and session headers",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "user_id", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "token", type: "varchar(255)", isNullable: false },
          { name: "ip", type: "inet", isNullable: false },
          { name: "expires_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "notifications",
        schema: "public",
        rowCount: 28400,
        description: "In-app notifications and real-time broadcasts",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "user_id", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "title", type: "varchar(100)", isNullable: false },
          { name: "message", type: "text", isNullable: false },
          { name: "is_read", type: "boolean", isNullable: false },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "comments",
        schema: "public",
        rowCount: 15400,
        description: "Discussion forum posts and question hints",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "user_id", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "problem_id", type: "uuid", isForeignKey: true, foreignKeyRef: "problems.id" },
          { name: "content", type: "text", isNullable: false },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "audit_logs",
        schema: "public",
        rowCount: 34200,
        description: "Real-time query execution events and mutation logs",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "user_id", type: "uuid", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "action", type: "varchar(100)", isNullable: false },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
    ],
    fks: [
      { from: "profiles", to: "users", label: "user_id → id" },
      { from: "teams", to: "users", label: "created_by → id" },
      { from: "team_members", to: "teams", label: "team_id → id" },
      { from: "team_members", to: "users", label: "user_id → id" },
      { from: "quizzes", to: "users", label: "created_by → id" },
      { from: "quizzes", to: "teams", label: "team_id → id" },
      { from: "problems", to: "quizzes", label: "quiz_id → id" },
      { from: "quiz_problems", to: "quizzes", label: "quiz_id → id" },
      { from: "quiz_problems", to: "problems", label: "problem_id → id" },
      { from: "submissions", to: "users", label: "user_id → id" },
      { from: "submissions", to: "problems", label: "problem_id → id" },
      { from: "storage_buckets", to: "users", label: "owner → id" },
      { from: "storage_objects", to: "storage_buckets", label: "bucket_id → id" },
      { from: "storage_objects", to: "users", label: "owner → id" },
      { from: "auth_sessions", to: "users", label: "user_id → id" },
      { from: "notifications", to: "users", label: "user_id → id" },
      { from: "comments", to: "users", label: "user_id → id" },
      { from: "comments", to: "problems", label: "problem_id → id" },
      { from: "audit_logs", to: "users", label: "user_id → id" },
    ],
  },

  Neon: {
    tables: [
      {
        tableName: "customers",
        schema: "public",
        rowCount: 5400,
        description: "Serverless customer accounts and contact information",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "company_name", type: "varchar(150)", isNullable: false },
          { name: "email", type: "varchar(255)", isNullable: false },
          { name: "tier", type: "varchar(30)", isNullable: false },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "branches",
        schema: "public",
        rowCount: 1200,
        description: "Database git-style serverless compute branches",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "customer_id", type: "uuid", isForeignKey: true, foreignKeyRef: "customers.id" },
          { name: "branch_name", type: "varchar(100)", isNullable: false },
          { name: "parent_branch", type: "varchar(100)", isNullable: true },
          { name: "status", type: "varchar(20)", isNullable: false },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "endpoints",
        schema: "public",
        rowCount: 2400,
        description: "Serverless proxy compute endpoints and host pools",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "branch_id", type: "uuid", isForeignKey: true, foreignKeyRef: "branches.id" },
          { name: "host", type: "varchar(255)", isNullable: false },
          { name: "port", type: "int4", isNullable: false },
          { name: "max_conns", type: "int4", isNullable: false },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "orders",
        schema: "public",
        rowCount: 18900,
        description: "Customer purchasing orders and branching transactions",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "customer_id", type: "uuid", isForeignKey: true, foreignKeyRef: "customers.id" },
          { name: "order_date", type: "date", isNullable: false },
          { name: "status", type: "varchar(20)", isNullable: false },
          { name: "total_amount", type: "numeric(10,2)", isNullable: false },
        ],
      },
      {
        tableName: "line_items",
        schema: "public",
        rowCount: 47200,
        description: "Itemized transaction entries on branch orders",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "order_id", type: "uuid", isForeignKey: true, foreignKeyRef: "orders.id" },
          { name: "item_name", type: "varchar(120)", isNullable: false },
          { name: "quantity", type: "int4", isNullable: false },
          { name: "amount", type: "numeric(10,2)", isNullable: false },
        ],
      },
      {
        tableName: "invoices",
        schema: "public",
        rowCount: 18900,
        description: "Generated invoices and tax statements",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "order_id", type: "uuid", isForeignKey: true, foreignKeyRef: "orders.id" },
          { name: "due_date", type: "date", isNullable: false },
          { name: "is_paid", type: "boolean", isNullable: false },
          { name: "total_amount", type: "numeric(10,2)", isNullable: false },
        ],
      },
      {
        tableName: "payments",
        schema: "public",
        rowCount: 17800,
        description: "Settled payments and processing provider logs",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "invoice_id", type: "uuid", isForeignKey: true, foreignKeyRef: "invoices.id" },
          { name: "amount_paid", type: "numeric(10,2)", isNullable: false },
          { name: "payment_method", type: "varchar(50)", isNullable: false },
          { name: "processed_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "payment_methods",
        schema: "public",
        rowCount: 6200,
        description: "Customer credit cards and payment methods",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "customer_id", type: "uuid", isForeignKey: true, foreignKeyRef: "customers.id" },
          { name: "provider", type: "varchar(50)", isNullable: false },
          { name: "last4", type: "varchar(4)", isNullable: false },
          { name: "is_default", type: "boolean", isNullable: false },
        ],
      },
      {
        tableName: "compute_metrics",
        schema: "public",
        rowCount: 150000,
        description: "Serverless autoscaling CPU and RAM telemetry",
        columns: [
          { name: "id", type: "bigserial", isPrimaryKey: true },
          { name: "endpoint_id", type: "uuid", isForeignKey: true, foreignKeyRef: "endpoints.id" },
          { name: "cpu_utilization", type: "float4", isNullable: false },
          { name: "memory_mb", type: "int4", isNullable: false },
          { name: "timestamp", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "storage_usage",
        schema: "public",
        rowCount: 45000,
        description: "Time-travel branching storage accounting",
        columns: [
          { name: "id", type: "bigserial", isPrimaryKey: true },
          { name: "customer_id", type: "uuid", isForeignKey: true, foreignKeyRef: "customers.id" },
          { name: "branch_id", type: "uuid", isForeignKey: true, foreignKeyRef: "branches.id" },
          { name: "bytes_used", type: "bigint", isNullable: false },
          { name: "recorded_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "access_tokens",
        schema: "public",
        rowCount: 3100,
        description: "API access credentials and OAuth client scopes",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "customer_id", type: "uuid", isForeignKey: true, foreignKeyRef: "customers.id" },
          { name: "token_hash", type: "varchar(64)", isNullable: false },
          { name: "permissions", type: "text", isNullable: false },
          { name: "expires_at", type: "timestamptz", isNullable: true },
        ],
      },
      {
        tableName: "audit_trail",
        schema: "public",
        rowCount: 78000,
        description: "Administrative console operations and branch lifecycle events",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "customer_id", type: "uuid", isForeignKey: true, foreignKeyRef: "customers.id" },
          { name: "event_type", type: "varchar(50)", isNullable: false },
          { name: "details", type: "text", isNullable: true },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
      {
        tableName: "backup_snapshots",
        schema: "public",
        rowCount: 840,
        description: "Point-in-time recovery WAL snapshots",
        columns: [
          { name: "id", type: "uuid", isPrimaryKey: true },
          { name: "branch_id", type: "uuid", isForeignKey: true, foreignKeyRef: "branches.id" },
          { name: "snapshot_size_gb", type: "float4", isNullable: false },
          { name: "created_at", type: "timestamptz", isNullable: false },
        ],
      },
    ],
    fks: [
      { from: "branches", to: "customers", label: "customer_id → id" },
      { from: "endpoints", to: "branches", label: "branch_id → id" },
      { from: "orders", to: "customers", label: "customer_id → id" },
      { from: "line_items", to: "orders", label: "order_id → id" },
      { from: "invoices", to: "orders", label: "order_id → id" },
      { from: "payments", to: "invoices", label: "invoice_id → id" },
      { from: "payment_methods", to: "customers", label: "customer_id → id" },
      { from: "compute_metrics", to: "endpoints", label: "endpoint_id → id" },
      { from: "storage_usage", to: "customers", label: "customer_id → id" },
      { from: "storage_usage", to: "branches", label: "branch_id → id" },
      { from: "access_tokens", to: "customers", label: "customer_id → id" },
      { from: "audit_trail", to: "customers", label: "customer_id → id" },
      { from: "backup_snapshots", to: "branches", label: "branch_id → id" },
    ],
  },

  MySQL: {
    tables: [
      {
        tableName: "users",
        schema: "mysql",
        rowCount: 8400,
        description: "Customer accounts and login authentication",
        columns: [
          { name: "id", type: "bigint", isPrimaryKey: true },
          { name: "email", type: "varchar(255)", isNullable: false },
          { name: "username", type: "varchar(64)", isNullable: false },
          { name: "role", type: "varchar(20)", isNullable: false },
          { name: "created_at", type: "datetime", isNullable: false },
        ],
      },
      {
        tableName: "addresses",
        schema: "mysql",
        rowCount: 11200,
        description: "Billing and shipping addresses",
        columns: [
          { name: "id", type: "bigint", isPrimaryKey: true },
          { name: "user_id", type: "bigint", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "street", type: "varchar(255)", isNullable: false },
          { name: "city", type: "varchar(100)", isNullable: false },
          { name: "state", type: "varchar(50)", isNullable: false },
          { name: "zip_code", type: "varchar(20)", isNullable: false },
          { name: "country", type: "varchar(50)", isNullable: false },
        ],
      },
      {
        tableName: "categories",
        schema: "mysql",
        rowCount: 48,
        description: "Product categories and hierarchical taxonomies",
        columns: [
          { name: "id", type: "int", isPrimaryKey: true },
          { name: "name", type: "varchar(100)", isNullable: false },
          { name: "slug", type: "varchar(100)", isNullable: false },
          { name: "parent_id", type: "int", isNullable: true },
        ],
      },
      {
        tableName: "suppliers",
        schema: "mysql",
        rowCount: 120,
        description: "Wholesale manufacturers and distributor contacts",
        columns: [
          { name: "id", type: "int", isPrimaryKey: true },
          { name: "name", type: "varchar(150)", isNullable: false },
          { name: "contact_email", type: "varchar(255)", isNullable: false },
          { name: "phone", type: "varchar(50)", isNullable: false },
          { name: "address", type: "varchar(255)", isNullable: true },
        ],
      },
      {
        tableName: "products",
        schema: "mysql",
        rowCount: 1850,
        description: "Store inventory catalog and pricing details",
        columns: [
          { name: "id", type: "bigint", isPrimaryKey: true },
          { name: "category_id", type: "int", isForeignKey: true, foreignKeyRef: "categories.id" },
          { name: "supplier_id", type: "int", isForeignKey: true, foreignKeyRef: "suppliers.id" },
          { name: "name", type: "varchar(200)", isNullable: false },
          { name: "sku", type: "varchar(50)", isNullable: false },
          { name: "price", type: "decimal(10,2)", isNullable: false },
          { name: "is_active", type: "tinyint(1)", isNullable: false },
        ],
      },
      {
        tableName: "product_variants",
        schema: "mysql",
        rowCount: 6200,
        description: "Product SKUs, colors, sizes, and price modifiers",
        columns: [
          { name: "id", type: "bigint", isPrimaryKey: true },
          { name: "product_id", type: "bigint", isForeignKey: true, foreignKeyRef: "products.id" },
          { name: "sku", type: "varchar(50)", isNullable: false },
          { name: "color", type: "varchar(30)", isNullable: true },
          { name: "size", type: "varchar(20)", isNullable: true },
          { name: "price_modifier", type: "decimal(10,2)", isNullable: false },
        ],
      },
      {
        tableName: "inventory",
        schema: "mysql",
        rowCount: 1850,
        description: "Warehouse stock levels and restocking thresholds",
        columns: [
          { name: "id", type: "bigint", isPrimaryKey: true },
          { name: "product_id", type: "bigint", isForeignKey: true, foreignKeyRef: "products.id" },
          { name: "stock_quantity", type: "int", isNullable: false },
          { name: "warehouse_code", type: "varchar(20)", isNullable: false },
          { name: "updated_at", type: "datetime", isNullable: false },
        ],
      },
      {
        tableName: "orders",
        schema: "mysql",
        rowCount: 24500,
        description: "E-commerce order transactions and fulfillment status",
        columns: [
          { name: "id", type: "bigint", isPrimaryKey: true },
          { name: "user_id", type: "bigint", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "shipping_address_id", type: "bigint", isForeignKey: true, foreignKeyRef: "addresses.id" },
          { name: "total_amount", type: "decimal(10,2)", isNullable: false },
          { name: "status", type: "varchar(32)", isNullable: false },
          { name: "created_at", type: "datetime", isNullable: false },
        ],
      },
      {
        tableName: "order_items",
        schema: "mysql",
        rowCount: 62000,
        description: "Line-items associated with fulfilled customer orders",
        columns: [
          { name: "id", type: "bigint", isPrimaryKey: true },
          { name: "order_id", type: "bigint", isForeignKey: true, foreignKeyRef: "orders.id" },
          { name: "product_id", type: "bigint", isForeignKey: true, foreignKeyRef: "products.id" },
          { name: "quantity", type: "int", isNullable: false },
          { name: "unit_price", type: "decimal(10,2)", isNullable: false },
        ],
      },
      {
        tableName: "payments",
        schema: "mysql",
        rowCount: 24100,
        description: "Payment gateway receipts and verification tokens",
        columns: [
          { name: "id", type: "bigint", isPrimaryKey: true },
          { name: "order_id", type: "bigint", isForeignKey: true, foreignKeyRef: "orders.id" },
          { name: "payment_gateway", type: "varchar(50)", isNullable: false },
          { name: "transaction_id", type: "varchar(100)", isNullable: false },
          { name: "status", type: "varchar(30)", isNullable: false },
          { name: "paid_at", type: "datetime", isNullable: false },
        ],
      },
      {
        tableName: "shipments",
        schema: "mysql",
        rowCount: 23800,
        description: "Fulfillment parcels, carrier tracking, and deliveries",
        columns: [
          { name: "id", type: "bigint", isPrimaryKey: true },
          { name: "order_id", type: "bigint", isForeignKey: true, foreignKeyRef: "orders.id" },
          { name: "tracking_number", type: "varchar(100)", isNullable: false },
          { name: "carrier", type: "varchar(50)", isNullable: false },
          { name: "status", type: "varchar(30)", isNullable: false },
          { name: "estimated_delivery", type: "date", isNullable: true },
        ],
      },
      {
        tableName: "reviews",
        schema: "mysql",
        rowCount: 9800,
        description: "Customer product reviews and verified ratings",
        columns: [
          { name: "id", type: "bigint", isPrimaryKey: true },
          { name: "user_id", type: "bigint", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "product_id", type: "bigint", isForeignKey: true, foreignKeyRef: "products.id" },
          { name: "rating", type: "int", isNullable: false },
          { name: "comment", type: "text", isNullable: true },
          { name: "created_at", type: "datetime", isNullable: false },
        ],
      },
      {
        tableName: "coupons",
        schema: "mysql",
        rowCount: 250,
        description: "Promotional vouchers and percentage discount codes",
        columns: [
          { name: "id", type: "int", isPrimaryKey: true },
          { name: "code", type: "varchar(50)", isNullable: false },
          { name: "discount_percent", type: "int", isNullable: false },
          { name: "valid_until", type: "datetime", isNullable: false },
          { name: "usage_count", type: "int", isNullable: false },
        ],
      },
      {
        tableName: "audit_events",
        schema: "mysql",
        rowCount: 54000,
        description: "Administrative mutations and critical system actions",
        columns: [
          { name: "id", type: "bigint", isPrimaryKey: true },
          { name: "user_id", type: "bigint", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "action", type: "varchar(100)", isNullable: false },
          { name: "timestamp", type: "datetime", isNullable: false },
        ],
      },
    ],
    fks: [
      { from: "addresses", to: "users", label: "user_id → id" },
      { from: "products", to: "categories", label: "category_id → id" },
      { from: "products", to: "suppliers", label: "supplier_id → id" },
      { from: "product_variants", to: "products", label: "product_id → id" },
      { from: "inventory", to: "products", label: "product_id → id" },
      { from: "orders", to: "users", label: "user_id → id" },
      { from: "orders", to: "addresses", label: "shipping_address_id → id" },
      { from: "order_items", to: "orders", label: "order_id → id" },
      { from: "order_items", to: "products", label: "product_id → id" },
      { from: "payments", to: "orders", label: "order_id → id" },
      { from: "shipments", to: "orders", label: "order_id → id" },
      { from: "reviews", to: "users", label: "user_id → id" },
      { from: "reviews", to: "products", label: "product_id → id" },
      { from: "audit_events", to: "users", label: "user_id → id" },
    ],
  },

  MongoDB: {
    tables: [
      {
        tableName: "users",
        schema: "mongodb",
        rowCount: 32000,
        description: "User profiles, roles, and authorization grants",
        columns: [
          { name: "_id", type: "ObjectId", isPrimaryKey: true },
          { name: "email", type: "String", isNullable: false },
          { name: "displayName", type: "String", isNullable: false },
          { name: "role", type: "String", isNullable: false },
          { name: "createdAt", type: "Date", isNullable: false },
        ],
      },
      {
        tableName: "workspaces",
        schema: "mongodb",
        rowCount: 450,
        description: "Collaborative project workspaces and access domains",
        columns: [
          { name: "_id", type: "ObjectId", isPrimaryKey: true },
          { name: "ownerId", type: "ObjectId", isForeignKey: true, foreignKeyRef: "users._id" },
          { name: "name", type: "String", isNullable: false },
          { name: "tier", type: "String", isNullable: false },
          { name: "createdAt", type: "Date", isNullable: false },
        ],
      },
      {
        tableName: "workspace_members",
        schema: "mongodb",
        rowCount: 2800,
        description: "User memberships and role permissions inside workspaces",
        columns: [
          { name: "_id", type: "ObjectId", isPrimaryKey: true },
          { name: "workspaceId", type: "ObjectId", isForeignKey: true, foreignKeyRef: "workspaces._id" },
          { name: "userId", type: "ObjectId", isForeignKey: true, foreignKeyRef: "users._id" },
          { name: "permissions", type: "Array<String>", isNullable: false },
        ],
      },
      {
        tableName: "collections",
        schema: "mongodb",
        rowCount: 1800,
        description: "Dynamic document collections and schema definitions",
        columns: [
          { name: "_id", type: "ObjectId", isPrimaryKey: true },
          { name: "workspaceId", type: "ObjectId", isForeignKey: true, foreignKeyRef: "workspaces._id" },
          { name: "name", type: "String", isNullable: false },
          { name: "schemaDefinition", type: "Object", isNullable: true },
          { name: "isPublic", type: "Boolean", isNullable: false },
        ],
      },
      {
        tableName: "documents",
        schema: "mongodb",
        rowCount: 145000,
        description: "Schema-less JSON document data stores",
        columns: [
          { name: "_id", type: "ObjectId", isPrimaryKey: true },
          { name: "collectionId", type: "ObjectId", isForeignKey: true, foreignKeyRef: "collections._id" },
          { name: "authorId", type: "ObjectId", isForeignKey: true, foreignKeyRef: "users._id" },
          { name: "data", type: "Object", isNullable: false },
          { name: "version", type: "Number", isNullable: false },
          { name: "updatedAt", type: "Date", isNullable: false },
        ],
      },
      {
        tableName: "revisions",
        schema: "mongodb",
        rowCount: 320000,
        description: "Document versioning history and revision diffs",
        columns: [
          { name: "_id", type: "ObjectId", isPrimaryKey: true },
          { name: "documentId", type: "ObjectId", isForeignKey: true, foreignKeyRef: "documents._id" },
          { name: "modifiedBy", type: "ObjectId", isForeignKey: true, foreignKeyRef: "users._id" },
          { name: "diff", type: "Object", isNullable: false },
          { name: "timestamp", type: "Date", isNullable: false },
        ],
      },
      {
        tableName: "file_assets",
        schema: "mongodb",
        rowCount: 18400,
        description: "GridFS and S3 file asset attachments",
        columns: [
          { name: "_id", type: "ObjectId", isPrimaryKey: true },
          { name: "workspaceId", type: "ObjectId", isForeignKey: true, foreignKeyRef: "workspaces._id" },
          { name: "fileName", type: "String", isNullable: false },
          { name: "mimeType", type: "String", isNullable: false },
          { name: "sizeBytes", type: "Number", isNullable: false },
          { name: "s3Url", type: "String", isNullable: false },
        ],
      },
      {
        tableName: "analytics_events",
        schema: "mongodb",
        rowCount: 890000,
        description: "Time-series interaction logs and analytics telemetry",
        columns: [
          { name: "_id", type: "ObjectId", isPrimaryKey: true },
          { name: "workspaceId", type: "ObjectId", isForeignKey: true, foreignKeyRef: "workspaces._id" },
          { name: "eventType", type: "String", isNullable: false },
          { name: "metadata", type: "Object", isNullable: true },
          { name: "timestamp", type: "Date", isNullable: false },
        ],
      },
      {
        tableName: "user_sessions",
        schema: "mongodb",
        rowCount: 14000,
        description: "Active user JWT sessions and login tokens",
        columns: [
          { name: "_id", type: "ObjectId", isPrimaryKey: true },
          { name: "userId", type: "ObjectId", isForeignKey: true, foreignKeyRef: "users._id" },
          { name: "device", type: "String", isNullable: false },
          { name: "ipAddress", type: "String", isNullable: false },
          { name: "expiresAt", type: "Date", isNullable: false },
        ],
      },
      {
        tableName: "integrations",
        schema: "mongodb",
        rowCount: 680,
        description: "Third-party connector webhooks and API credentials",
        columns: [
          { name: "_id", type: "ObjectId", isPrimaryKey: true },
          { name: "workspaceId", type: "ObjectId", isForeignKey: true, foreignKeyRef: "workspaces._id" },
          { name: "provider", type: "String", isNullable: false },
          { name: "config", type: "Object", isNullable: false },
          { name: "isActive", type: "Boolean", isNullable: false },
        ],
      },
      {
        tableName: "notifications",
        schema: "mongodb",
        rowCount: 45000,
        description: "In-app push notifications and alerts",
        columns: [
          { name: "_id", type: "ObjectId", isPrimaryKey: true },
          { name: "userId", type: "ObjectId", isForeignKey: true, foreignKeyRef: "users._id" },
          { name: "message", type: "String", isNullable: false },
          { name: "isRead", type: "Boolean", isNullable: false },
          { name: "createdAt", type: "Date", isNullable: false },
        ],
      },
      {
        tableName: "system_logs",
        schema: "mongodb",
        rowCount: 540000,
        description: "Cluster operations and service error traces",
        columns: [
          { name: "_id", type: "ObjectId", isPrimaryKey: true },
          { name: "service", type: "String", isNullable: false },
          { name: "level", type: "String", isNullable: false },
          { name: "message", type: "String", isNullable: false },
          { name: "timestamp", type: "Date", isNullable: false },
        ],
      },
    ],
    fks: [
      { from: "workspaces", to: "users", label: "ownerId → _id" },
      { from: "workspace_members", to: "workspaces", label: "workspaceId → _id" },
      { from: "workspace_members", to: "users", label: "userId → _id" },
      { from: "collections", to: "workspaces", label: "workspaceId → _id" },
      { from: "documents", to: "collections", label: "collectionId → _id" },
      { from: "documents", to: "users", label: "authorId → _id" },
      { from: "revisions", to: "documents", label: "documentId → _id" },
      { from: "revisions", to: "users", label: "modifiedBy → _id" },
      { from: "file_assets", to: "workspaces", label: "workspaceId → _id" },
      { from: "analytics_events", to: "workspaces", label: "workspaceId → _id" },
      { from: "user_sessions", to: "users", label: "userId → _id" },
      { from: "integrations", to: "workspaces", label: "workspaceId → _id" },
      { from: "notifications", to: "users", label: "userId → _id" },
    ],
  },

  Snowflake: {
    tables: [
      {
        tableName: "dim_customers",
        schema: "analytics",
        rowCount: 85000,
        description: "Customer dimensional attributes and segmentation",
        columns: [
          { name: "customer_id", type: "number(38,0)", isPrimaryKey: true },
          { name: "segment", type: "varchar(50)", isNullable: false },
          { name: "region", type: "varchar(50)", isNullable: false },
          { name: "country", type: "varchar(50)", isNullable: false },
          { name: "lifetime_value", type: "number(12,2)", isNullable: false },
        ],
      },
      {
        tableName: "dim_stores",
        schema: "analytics",
        rowCount: 250,
        description: "Physical retail locations and distribution hubs",
        columns: [
          { name: "store_id", type: "number(38,0)", isPrimaryKey: true },
          { name: "store_name", type: "varchar(100)", isNullable: false },
          { name: "region", type: "varchar(50)", isNullable: false },
          { name: "square_footage", type: "number(10,0)", isNullable: false },
          { name: "open_date", type: "date", isNullable: false },
        ],
      },
      {
        tableName: "dim_products",
        schema: "analytics",
        rowCount: 12000,
        description: "Product catalog hierarchy and department metadata",
        columns: [
          { name: "product_id", type: "number(38,0)", isPrimaryKey: true },
          { name: "sku", type: "varchar(50)", isNullable: false },
          { name: "product_name", type: "varchar(150)", isNullable: false },
          { name: "category", type: "varchar(80)", isNullable: false },
          { name: "unit_cost", type: "number(10,2)", isNullable: false },
        ],
      },
      {
        tableName: "dim_dates",
        schema: "analytics",
        rowCount: 3650,
        description: "Calendar date dimension with fiscal mapping",
        columns: [
          { name: "date_id", type: "number(38,0)", isPrimaryKey: true },
          { name: "full_date", type: "date", isNullable: false },
          { name: "fiscal_year", type: "number(4,0)", isNullable: false },
          { name: "fiscal_quarter", type: "varchar(10)", isNullable: false },
          { name: "is_weekend", type: "boolean", isNullable: false },
        ],
      },
      {
        tableName: "dim_channels",
        schema: "analytics",
        rowCount: 18,
        description: "Omnichannel marketing and sales attribution funnels",
        columns: [
          { name: "channel_id", type: "number(38,0)", isPrimaryKey: true },
          { name: "channel_name", type: "varchar(50)", isNullable: false },
          { name: "channel_type", type: "varchar(30)", isNullable: false },
          { name: "attribution_weight", type: "number(4,2)", isNullable: false },
        ],
      },
      {
        tableName: "fact_sales",
        schema: "analytics",
        rowCount: 2450000,
        description: "Centralized analytical fact table for revenue and volumes",
        columns: [
          { name: "sale_id", type: "number(38,0)", isPrimaryKey: true },
          { name: "customer_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "dim_customers.customer_id" },
          { name: "product_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "dim_products.product_id" },
          { name: "store_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "dim_stores.store_id" },
          { name: "date_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "dim_dates.date_id" },
          { name: "channel_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "dim_channels.channel_id" },
          { name: "net_revenue", type: "number(14,2)", isNullable: false },
          { name: "quantity", type: "number(10,0)", isNullable: false },
        ],
      },
      {
        tableName: "fact_inventory_snapshot",
        schema: "analytics",
        rowCount: 890000,
        description: "Daily inventory stock positions across stores",
        columns: [
          { name: "snapshot_id", type: "number(38,0)", isPrimaryKey: true },
          { name: "product_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "dim_products.product_id" },
          { name: "store_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "dim_stores.store_id" },
          { name: "date_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "dim_dates.date_id" },
          { name: "on_hand_qty", type: "number(10,0)", isNullable: false },
          { name: "safety_stock", type: "number(10,0)", isNullable: false },
        ],
      },
      {
        tableName: "fact_order_fulfillments",
        schema: "analytics",
        rowCount: 1200000,
        description: "Fulfillment delivery times and courier reliability",
        columns: [
          { name: "fulfillment_id", type: "number(38,0)", isPrimaryKey: true },
          { name: "sale_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "fact_sales.sale_id" },
          { name: "store_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "dim_stores.store_id" },
          { name: "date_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "dim_dates.date_id" },
          { name: "fulfillment_time_hrs", type: "number(6,2)", isNullable: false },
          { name: "status", type: "varchar(30)", isNullable: false },
        ],
      },
      {
        tableName: "fact_customer_retention",
        schema: "analytics",
        rowCount: 450000,
        description: "Cohort retention analysis and recurring revenue metrics",
        columns: [
          { name: "cohort_id", type: "number(38,0)", isPrimaryKey: true },
          { name: "customer_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "dim_customers.customer_id" },
          { name: "start_date_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "dim_dates.date_id" },
          { name: "repeat_purchase_count", type: "number(6,0)", isNullable: false },
        ],
      },
      {
        tableName: "agg_monthly_revenue",
        schema: "analytics",
        rowCount: 1200,
        description: "Materialized rollup of monthly revenue by sales channel",
        columns: [
          { name: "record_id", type: "number(38,0)", isPrimaryKey: true },
          { name: "fiscal_year", type: "number(4,0)", isNullable: false },
          { name: "fiscal_month", type: "number(2,0)", isNullable: false },
          { name: "channel_id", type: "number(38,0)", isForeignKey: true, foreignKeyRef: "dim_channels.channel_id" },
          { name: "total_revenue", type: "number(16,2)", isNullable: false },
        ],
      },
      {
        tableName: "agg_regional_sales",
        schema: "analytics",
        rowCount: 960,
        description: "Aggregated performance summary across sales territories",
        columns: [
          { name: "record_id", type: "number(38,0)", isPrimaryKey: true },
          { name: "region", type: "varchar(50)", isNullable: false },
          { name: "fiscal_quarter", type: "varchar(10)", isNullable: false },
          { name: "total_units", type: "number(12,0)", isNullable: false },
          { name: "net_margin", type: "number(14,2)", isNullable: false },
        ],
      },
      {
        tableName: "staging_raw_events",
        schema: "staging",
        rowCount: 5400000,
        description: "High-throughput ingested JSON events prior to transformation",
        columns: [
          { name: "raw_event_id", type: "varchar(64)", isPrimaryKey: true },
          { name: "payload", type: "variant", isNullable: false },
          { name: "ingested_at", type: "timestamp_ntz", isNullable: false },
          { name: "source_system", type: "varchar(50)", isNullable: false },
        ],
      },
      {
        tableName: "data_pipeline_runs",
        schema: "orchestration",
        rowCount: 4500,
        description: "dbt and Snowpipe execution logs and row throughput",
        columns: [
          { name: "run_id", type: "varchar(64)", isPrimaryKey: true },
          { name: "pipeline_name", type: "varchar(100)", isNullable: false },
          { name: "status", type: "varchar(20)", isNullable: false },
          { name: "rows_loaded", type: "number(12,0)", isNullable: false },
          { name: "duration_sec", type: "number(8,2)", isNullable: false },
          { name: "executed_at", type: "timestamp_ntz", isNullable: false },
        ],
      },
      {
        tableName: "governance_audit",
        schema: "governance",
        rowCount: 68000,
        description: "Snowflake query access audit and warehouse credit consumption",
        columns: [
          { name: "audit_id", type: "varchar(64)", isPrimaryKey: true },
          { name: "user_name", type: "varchar(100)", isNullable: false },
          { name: "query_text", type: "text", isNullable: false },
          { name: "bytes_scanned", type: "number(18,0)", isNullable: false },
          { name: "timestamp", type: "timestamp_ltz", isNullable: false },
        ],
      },
    ],
    fks: [
      { from: "fact_sales", to: "dim_customers", label: "customer_id → customer_id" },
      { from: "fact_sales", to: "dim_products", label: "product_id → product_id" },
      { from: "fact_sales", to: "dim_stores", label: "store_id → store_id" },
      { from: "fact_sales", to: "dim_dates", label: "date_id → date_id" },
      { from: "fact_sales", to: "dim_channels", label: "channel_id → channel_id" },
      { from: "fact_inventory_snapshot", to: "dim_products", label: "product_id → product_id" },
      { from: "fact_inventory_snapshot", to: "dim_stores", label: "store_id → store_id" },
      { from: "fact_inventory_snapshot", to: "dim_dates", label: "date_id → date_id" },
      { from: "fact_order_fulfillments", to: "fact_sales", label: "sale_id → sale_id" },
      { from: "fact_order_fulfillments", to: "dim_stores", label: "store_id → store_id" },
      { from: "fact_order_fulfillments", to: "dim_dates", label: "date_id → date_id" },
      { from: "fact_customer_retention", to: "dim_customers", label: "customer_id → customer_id" },
      { from: "fact_customer_retention", to: "dim_dates", label: "start_date_id → date_id" },
      { from: "agg_monthly_revenue", to: "dim_channels", label: "channel_id → channel_id" },
    ],
  },

  BigQuery: {
    tables: [
      {
        tableName: "events_raw",
        schema: "analytics_warehouse",
        rowCount: 14500000,
        description: "Partitioned clickstream and event ingestion pipeline",
        columns: [
          { name: "event_id", type: "STRING", isPrimaryKey: true },
          { name: "event_timestamp", type: "TIMESTAMP", isNullable: false },
          { name: "user_pseudo_id", type: "STRING", isNullable: false },
          { name: "event_name", type: "STRING", isNullable: false },
          { name: "event_params", type: "JSON", isNullable: true },
        ],
      },
      {
        tableName: "user_pseudo_ids",
        schema: "analytics_warehouse",
        rowCount: 820000,
        description: "Anonymous client device and browser identification registry",
        columns: [
          { name: "user_pseudo_id", type: "STRING", isPrimaryKey: true },
          { name: "first_touch_timestamp", type: "TIMESTAMP", isNullable: false },
          { name: "geo_country", type: "STRING", isNullable: false },
          { name: "device_category", type: "STRING", isNullable: false },
        ],
      },
      {
        tableName: "traffic_sources",
        schema: "analytics_warehouse",
        rowCount: 450000,
        description: "First-touch and last-click attribution tracking",
        columns: [
          { name: "source_id", type: "STRING", isPrimaryKey: true },
          { name: "user_pseudo_id", type: "STRING", isForeignKey: true, foreignKeyRef: "user_pseudo_ids.user_pseudo_id" },
          { name: "source", type: "STRING", isNullable: false },
          { name: "medium", type: "STRING", isNullable: false },
          { name: "campaign", type: "STRING", isNullable: false },
        ],
      },
      {
        tableName: "daily_user_metrics",
        schema: "analytics_warehouse",
        rowCount: 340000,
        description: "Aggregated daily active user KPIs and retention cohorts",
        columns: [
          { name: "date", type: "DATE", isPrimaryKey: true },
          { name: "user_pseudo_id", type: "STRING", isPrimaryKey: true, isForeignKey: true, foreignKeyRef: "user_pseudo_ids.user_pseudo_id" },
          { name: "session_count", type: "INT64", isNullable: false },
          { name: "duration_seconds", type: "FLOAT64", isNullable: false },
          { name: "screen_views", type: "INT64", isNullable: false },
        ],
      },
      {
        tableName: "conversions",
        schema: "analytics_warehouse",
        rowCount: 82000,
        description: "Completed purchase funnels and revenue conversions",
        columns: [
          { name: "conversion_id", type: "STRING", isPrimaryKey: true },
          { name: "user_pseudo_id", type: "STRING", isForeignKey: true, foreignKeyRef: "user_pseudo_ids.user_pseudo_id" },
          { name: "revenue_usd", type: "FLOAT64", isNullable: false },
          { name: "campaign_source", type: "STRING", isNullable: false },
          { name: "conversion_time", type: "TIMESTAMP", isNullable: false },
        ],
      },
      {
        tableName: "ad_spend_attribution",
        schema: "analytics_warehouse",
        rowCount: 45000,
        description: "Marketing spend attribution and campaign ROI",
        columns: [
          { name: "spend_id", type: "STRING", isPrimaryKey: true },
          { name: "campaign_id", type: "STRING", isNullable: false },
          { name: "platform", type: "STRING", isNullable: false },
          { name: "daily_cost", type: "FLOAT64", isNullable: false },
          { name: "clicks", type: "INT64", isNullable: false },
          { name: "impressions", type: "INT64", isNullable: false },
          { name: "date", type: "DATE", isNullable: false },
        ],
      },
      {
        tableName: "campaign_conversions",
        schema: "analytics_warehouse",
        rowCount: 12000,
        description: "Performance metrics cross-joined by ad campaign",
        columns: [
          { name: "campaign_id", type: "STRING", isPrimaryKey: true },
          { name: "campaign_name", type: "STRING", isNullable: false },
          { name: "total_conversions", type: "INT64", isNullable: false },
          { name: "total_spend", type: "FLOAT64", isNullable: false },
          { name: "cpa", type: "FLOAT64", isNullable: false },
        ],
      },
      {
        tableName: "customer_lifetime_value",
        schema: "analytics_warehouse",
        rowCount: 150000,
        description: "Predictive ML customer lifetime value and churn risk",
        columns: [
          { name: "user_pseudo_id", type: "STRING", isPrimaryKey: true, isForeignKey: true, foreignKeyRef: "user_pseudo_ids.user_pseudo_id" },
          { name: "predicted_clv", type: "FLOAT64", isNullable: false },
          { name: "actual_revenue", type: "FLOAT64", isNullable: false },
          { name: "churn_risk_score", type: "FLOAT64", isNullable: false },
        ],
      },
      {
        tableName: "attribution_touchpoints",
        schema: "analytics_warehouse",
        rowCount: 980000,
        description: "Multi-touch journey events preceding conversion",
        columns: [
          { name: "touchpoint_id", type: "STRING", isPrimaryKey: true },
          { name: "user_pseudo_id", type: "STRING", isForeignKey: true, foreignKeyRef: "user_pseudo_ids.user_pseudo_id" },
          { name: "touchpoint_sequence", type: "INT64", isNullable: false },
          { name: "channel", type: "STRING", isNullable: false },
          { name: "timestamp", type: "TIMESTAMP", isNullable: false },
        ],
      },
      {
        tableName: "churn_predictions",
        schema: "analytics_warehouse",
        rowCount: 85000,
        description: "Machine learning churn classification inferences",
        columns: [
          { name: "prediction_id", type: "STRING", isPrimaryKey: true },
          { name: "user_pseudo_id", type: "STRING", isForeignKey: true, foreignKeyRef: "user_pseudo_ids.user_pseudo_id" },
          { name: "churn_probability", type: "FLOAT64", isNullable: false },
          { name: "calculated_at", type: "TIMESTAMP", isNullable: false },
        ],
      },
      {
        tableName: "bi_dashboard_metrics",
        schema: "analytics_warehouse",
        rowCount: 1400,
        description: "Pre-aggregated metrics for Looker and Tableau dashboards",
        columns: [
          { name: "metric_date", type: "DATE", isPrimaryKey: true },
          { name: "total_dau", type: "INT64", isNullable: false },
          { name: "total_mau", type: "INT64", isNullable: false },
          { name: "total_revenue", type: "FLOAT64", isNullable: false },
          { name: "conversion_rate", type: "FLOAT64", isNullable: false },
        ],
      },
      {
        tableName: "ml_feature_store",
        schema: "analytics_warehouse",
        rowCount: 2500000,
        description: "Feature repository for recommendation models",
        columns: [
          { name: "feature_id", type: "STRING", isPrimaryKey: true },
          { name: "entity_id", type: "STRING", isNullable: false },
          { name: "feature_name", type: "STRING", isNullable: false },
          { name: "feature_value", type: "FLOAT64", isNullable: false },
          { name: "feature_timestamp", type: "TIMESTAMP", isNullable: false },
        ],
      },
      {
        tableName: "query_execution_audit",
        schema: "analytics_warehouse",
        rowCount: 64000,
        description: "BigQuery job execution costs and scanned data bytes",
        columns: [
          { name: "query_id", type: "STRING", isPrimaryKey: true },
          { name: "user_email", type: "STRING", isNullable: false },
          { name: "bytes_processed", type: "INT64", isNullable: false },
          { name: "cache_hit", type: "BOOLEAN", isNullable: false },
          { name: "execution_time_ms", type: "INT64", isNullable: false },
        ],
      },
    ],
    fks: [
      { from: "traffic_sources", to: "user_pseudo_ids", label: "user_pseudo_id → user_pseudo_id" },
      { from: "daily_user_metrics", to: "user_pseudo_ids", label: "user_pseudo_id → user_pseudo_id" },
      { from: "conversions", to: "user_pseudo_ids", label: "user_pseudo_id → user_pseudo_id" },
      { from: "customer_lifetime_value", to: "user_pseudo_ids", label: "user_pseudo_id → user_pseudo_id" },
      { from: "attribution_touchpoints", to: "user_pseudo_ids", label: "user_pseudo_id → user_pseudo_id" },
      { from: "churn_predictions", to: "user_pseudo_ids", label: "user_pseudo_id → user_pseudo_id" },
    ],
  },

  SQLite: {
    tables: [
      {
        tableName: "users",
        schema: "main",
        rowCount: 120,
        description: "Local desktop client user credentials and profiles",
        columns: [
          { name: "id", type: "INTEGER", isPrimaryKey: true },
          { name: "username", type: "TEXT", isNullable: false },
          { name: "email", type: "TEXT", isNullable: false },
          { name: "password_hash", type: "TEXT", isNullable: false },
          { name: "created_at", type: "TEXT", isNullable: false },
        ],
      },
      {
        tableName: "app_settings",
        schema: "main",
        rowCount: 1,
        description: "Application preferences and configuration flags",
        columns: [
          { name: "id", type: "INTEGER", isPrimaryKey: true },
          { name: "user_id", type: "INTEGER", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "theme", type: "TEXT", isNullable: false },
          { name: "language", type: "TEXT", isNullable: false },
          { name: "notifications_enabled", type: "INTEGER", isNullable: false },
          { name: "sync_interval", type: "INTEGER", isNullable: false },
        ],
      },
      {
        tableName: "workspaces",
        schema: "main",
        rowCount: 8,
        description: "Local productivity project workspaces",
        columns: [
          { name: "id", type: "INTEGER", isPrimaryKey: true },
          { name: "user_id", type: "INTEGER", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "name", type: "TEXT", isNullable: false },
          { name: "color", type: "TEXT", isNullable: false },
          { name: "icon", type: "TEXT", isNullable: true },
          { name: "created_at", type: "TEXT", isNullable: false },
        ],
      },
      {
        tableName: "tasks",
        schema: "main",
        rowCount: 1420,
        description: "Offline-first tasks, priority flags, and deadlines",
        columns: [
          { name: "id", type: "INTEGER", isPrimaryKey: true },
          { name: "workspace_id", type: "INTEGER", isForeignKey: true, foreignKeyRef: "workspaces.id" },
          { name: "title", type: "TEXT", isNullable: false },
          { name: "description", type: "TEXT", isNullable: true },
          { name: "is_completed", type: "INTEGER", isNullable: false },
          { name: "priority", type: "TEXT", isNullable: false },
          { name: "due_date", type: "TEXT", isNullable: true },
        ],
      },
      {
        tableName: "task_tags",
        schema: "main",
        rowCount: 3200,
        description: "Categorical tags assigned to individual tasks",
        columns: [
          { name: "id", type: "INTEGER", isPrimaryKey: true },
          { name: "task_id", type: "INTEGER", isForeignKey: true, foreignKeyRef: "tasks.id" },
          { name: "tag_name", type: "TEXT", isNullable: false },
          { name: "color", type: "TEXT", isNullable: false },
        ],
      },
      {
        tableName: "attachments",
        schema: "main",
        rowCount: 450,
        description: "Local media files and document attachments",
        columns: [
          { name: "id", type: "INTEGER", isPrimaryKey: true },
          { name: "task_id", type: "INTEGER", isForeignKey: true, foreignKeyRef: "tasks.id" },
          { name: "file_name", type: "TEXT", isNullable: false },
          { name: "file_path", type: "TEXT", isNullable: false },
          { name: "file_size_bytes", type: "INTEGER", isNullable: false },
          { name: "uploaded_at", type: "TEXT", isNullable: false },
        ],
      },
      {
        tableName: "comments",
        schema: "main",
        rowCount: 2100,
        description: "Collaborator notes and activity updates on tasks",
        columns: [
          { name: "id", type: "INTEGER", isPrimaryKey: true },
          { name: "task_id", type: "INTEGER", isForeignKey: true, foreignKeyRef: "tasks.id" },
          { name: "user_id", type: "INTEGER", isForeignKey: true, foreignKeyRef: "users.id" },
          { name: "content", type: "TEXT", isNullable: false },
          { name: "created_at", type: "TEXT", isNullable: false },
        ],
      },
      {
        tableName: "reminders",
        schema: "main",
        rowCount: 680,
        description: "Local notification schedule alerts and alarms",
        columns: [
          { name: "id", type: "INTEGER", isPrimaryKey: true },
          { name: "task_id", type: "INTEGER", isForeignKey: true, foreignKeyRef: "tasks.id" },
          { name: "remind_at", type: "TEXT", isNullable: false },
          { name: "is_triggered", type: "INTEGER", isNullable: false },
        ],
      },
      {
        tableName: "local_cache",
        schema: "main",
        rowCount: 4500,
        description: "Key-value transient blob cache for offline query support",
        columns: [
          { name: "id", type: "INTEGER", isPrimaryKey: true },
          { name: "cache_key", type: "TEXT", isNullable: false },
          { name: "payload", type: "BLOB", isNullable: false },
          { name: "expires_at", type: "TEXT", isNullable: false },
        ],
      },
      {
        tableName: "sync_queue",
        schema: "main",
        rowCount: 120,
        description: "Outbox journal queue for upstream cloud sync operations",
        columns: [
          { name: "id", type: "INTEGER", isPrimaryKey: true },
          { name: "operation", type: "TEXT", isNullable: false },
          { name: "entity_type", type: "TEXT", isNullable: false },
          { name: "entity_id", type: "TEXT", isNullable: false },
          { name: "payload", type: "TEXT", isNullable: false },
          { name: "synced", type: "INTEGER", isNullable: false },
        ],
      },
      {
        tableName: "device_registry",
        schema: "main",
        rowCount: 4,
        description: "Authorized client device hardware fingerprints",
        columns: [
          { name: "id", type: "INTEGER", isPrimaryKey: true },
          { name: "device_id", type: "TEXT", isNullable: false },
          { name: "platform", type: "TEXT", isNullable: false },
          { name: "os_version", type: "TEXT", isNullable: false },
          { name: "last_active", type: "TEXT", isNullable: false },
        ],
      },
      {
        tableName: "local_audit",
        schema: "main",
        rowCount: 8900,
        description: "Local database change tracking and transactional journal",
        columns: [
          { name: "id", type: "INTEGER", isPrimaryKey: true },
          { name: "action", type: "TEXT", isNullable: false },
          { name: "timestamp", type: "TEXT", isNullable: false },
        ],
      },
      {
        tableName: "db_migrations",
        schema: "main",
        rowCount: 24,
        description: "Applied SQLite schema migration scripts",
        columns: [
          { name: "id", type: "INTEGER", isPrimaryKey: true },
          { name: "version", type: "INTEGER", isNullable: false },
          { name: "applied_at", type: "TEXT", isNullable: false },
        ],
      },
    ],
    fks: [
      { from: "app_settings", to: "users", label: "user_id → id" },
      { from: "workspaces", to: "users", label: "user_id → id" },
      { from: "tasks", to: "workspaces", label: "workspace_id → id" },
      { from: "task_tags", to: "tasks", label: "task_id → id" },
      { from: "attachments", to: "tasks", label: "task_id → id" },
      { from: "comments", to: "tasks", label: "task_id → id" },
      { from: "comments", to: "users", label: "user_id → id" },
      { from: "reminders", to: "tasks", label: "task_id → id" },
    ],
  },

  CockroachDB: {
    tables: [
      {
        tableName: "clusters",
        schema: "public",
        rowCount: 4,
        description: "Distributed CockroachDB multi-region deployment clusters",
        columns: [
          { name: "id", type: "UUID", isPrimaryKey: true },
          { name: "cluster_name", type: "VARCHAR(100)", isNullable: false },
          { name: "cloud_provider", type: "VARCHAR(50)", isNullable: false },
          { name: "topology", type: "VARCHAR(50)", isNullable: false },
          { name: "created_at", type: "TIMESTAMPTZ", isNullable: false },
        ],
      },
      {
        tableName: "nodes",
        schema: "public",
        rowCount: 24,
        description: "Raft consensus worker nodes across regions",
        columns: [
          { name: "id", type: "INT4", isPrimaryKey: true },
          { name: "cluster_id", type: "UUID", isForeignKey: true, foreignKeyRef: "clusters.id" },
          { name: "node_ip", type: "INET", isNullable: false },
          { name: "region", type: "VARCHAR(50)", isNullable: false },
          { name: "zone", type: "VARCHAR(50)", isNullable: false },
          { name: "status", type: "VARCHAR(20)", isNullable: false },
        ],
      },
      {
        tableName: "regions",
        schema: "public",
        rowCount: 6,
        description: "Geo-partitioned survivor locations and survival goals",
        columns: [
          { name: "id", type: "UUID", isPrimaryKey: true },
          { name: "cluster_id", type: "UUID", isForeignKey: true, foreignKeyRef: "clusters.id" },
          { name: "region_name", type: "VARCHAR(50)", isNullable: false },
          { name: "latency_target_ms", type: "INT4", isNullable: false },
        ],
      },
      {
        tableName: "partitions",
        schema: "public",
        rowCount: 72,
        description: "Row-level locality configurations and leaseholder ranges",
        columns: [
          { name: "id", type: "UUID", isPrimaryKey: true },
          { name: "table_name", type: "VARCHAR(100)", isNullable: false },
          { name: "region_id", type: "UUID", isForeignKey: true, foreignKeyRef: "regions.id" },
          { name: "partition_range", type: "VARCHAR(100)", isNullable: false },
        ],
      },
      {
        tableName: "customers",
        schema: "public",
        rowCount: 18500,
        description: "Enterprise customer entities and jurisdiction assignments",
        columns: [
          { name: "id", type: "UUID", isPrimaryKey: true },
          { name: "legal_name", type: "VARCHAR(200)", isNullable: false },
          { name: "tax_id", type: "VARCHAR(50)", isNullable: false },
          { name: "jurisdiction", type: "VARCHAR(50)", isNullable: false },
          { name: "created_at", type: "TIMESTAMPTZ", isNullable: false },
        ],
      },
      {
        tableName: "accounts",
        schema: "public",
        rowCount: 45000,
        description: "Multi-currency bank accounts with serializable isolation",
        columns: [
          { name: "id", type: "UUID", isPrimaryKey: true },
          { name: "customer_id", type: "UUID", isForeignKey: true, foreignKeyRef: "customers.id" },
          { name: "currency", type: "VARCHAR(3)", isNullable: false },
          { name: "balance", type: "DECIMAL(18,4)", isNullable: false },
          { name: "account_status", type: "VARCHAR(20)", isNullable: false },
          { name: "created_at", type: "TIMESTAMPTZ", isNullable: false },
        ],
      },
      {
        tableName: "wallets",
        schema: "public",
        rowCount: 45000,
        description: "Customer escrow wallets and reserved settlement balances",
        columns: [
          { name: "id", type: "UUID", isPrimaryKey: true },
          { name: "account_id", type: "UUID", isForeignKey: true, foreignKeyRef: "accounts.id" },
          { name: "wallet_type", type: "VARCHAR(30)", isNullable: false },
          { name: "available_balance", type: "DECIMAL(18,4)", isNullable: false },
          { name: "locked_balance", type: "DECIMAL(18,4)", isNullable: false },
        ],
      },
      {
        tableName: "transactions",
        schema: "public",
        rowCount: 890000,
        description: "ACID-compliant atomic monetary value transfers",
        columns: [
          { name: "id", type: "UUID", isPrimaryKey: true },
          { name: "from_account_id", type: "UUID", isForeignKey: true, foreignKeyRef: "accounts.id" },
          { name: "to_account_id", type: "UUID", isForeignKey: true, foreignKeyRef: "accounts.id" },
          { name: "amount", type: "DECIMAL(18,4)", isNullable: false },
          { name: "currency", type: "VARCHAR(3)", isNullable: false },
          { name: "status", type: "VARCHAR(20)", isNullable: false },
          { name: "created_at", type: "TIMESTAMPTZ", isNullable: false },
        ],
      },
      {
        tableName: "ledger_entries",
        schema: "public",
        rowCount: 1780000,
        description: "Double-entry bookkeeping journal debit/credit lines",
        columns: [
          { name: "id", type: "UUID", isPrimaryKey: true },
          { name: "transaction_id", type: "UUID", isForeignKey: true, foreignKeyRef: "transactions.id" },
          { name: "account_id", type: "UUID", isForeignKey: true, foreignKeyRef: "accounts.id" },
          { name: "direction", type: "VARCHAR(6)", isNullable: false },
          { name: "amount", type: "DECIMAL(18,4)", isNullable: false },
          { name: "created_at", type: "TIMESTAMPTZ", isNullable: false },
        ],
      },
      {
        tableName: "settlements",
        schema: "public",
        rowCount: 120000,
        description: "Clearing house interbank settlement batches",
        columns: [
          { name: "id", type: "UUID", isPrimaryKey: true },
          { name: "transaction_id", type: "UUID", isForeignKey: true, foreignKeyRef: "transactions.id" },
          { name: "clearing_house", type: "VARCHAR(100)", isNullable: false },
          { name: "batch_id", type: "VARCHAR(64)", isNullable: false },
          { name: "settled_at", type: "TIMESTAMPTZ", isNullable: false },
        ],
      },
      {
        tableName: "idempotency_keys",
        schema: "public",
        rowCount: 850000,
        description: "Distributed duplicate payment prevention registry",
        columns: [
          { name: "id", type: "UUID", isPrimaryKey: true },
          { name: "key_hash", type: "VARCHAR(64)", isNullable: false },
          { name: "request_payload", type: "TEXT", isNullable: false },
          { name: "response_payload", type: "TEXT", isNullable: true },
          { name: "locked_until", type: "TIMESTAMPTZ", isNullable: false },
        ],
      },
      {
        tableName: "distributed_locks",
        schema: "public",
        rowCount: 1200,
        description: "Raft consensus mutual exclusion locks for distributed workers",
        columns: [
          { name: "id", type: "UUID", isPrimaryKey: true },
          { name: "resource_id", type: "VARCHAR(128)", isNullable: false },
          { name: "held_by_node", type: "INT4", isForeignKey: true, foreignKeyRef: "nodes.id" },
          { name: "expires_at", type: "TIMESTAMPTZ", isNullable: false },
        ],
      },
      {
        tableName: "currency_rates",
        schema: "public",
        rowCount: 320,
        description: "Spot FX currency exchange rates for instant conversions",
        columns: [
          { name: "id", type: "UUID", isPrimaryKey: true },
          { name: "base_currency", type: "VARCHAR(3)", isNullable: false },
          { name: "target_currency", type: "VARCHAR(3)", isNullable: false },
          { name: "rate", type: "DECIMAL(12,6)", isNullable: false },
          { name: "effective_at", type: "TIMESTAMPTZ", isNullable: false },
        ],
      },
      {
        tableName: "audit_trail",
        schema: "public",
        rowCount: 245000,
        description: "Consensus-backed immutable transaction audit records",
        columns: [
          { name: "id", type: "UUID", isPrimaryKey: true },
          { name: "transaction_id", type: "UUID", isForeignKey: true, foreignKeyRef: "transactions.id" },
          { name: "node_id", type: "INT4", isForeignKey: true, foreignKeyRef: "nodes.id" },
          { name: "action", type: "VARCHAR(100)", isNullable: false },
          { name: "signature", type: "VARCHAR(256)", isNullable: false },
          { name: "timestamp", type: "TIMESTAMPTZ", isNullable: false },
        ],
      },
    ],
    fks: [
      { from: "nodes", to: "clusters", label: "cluster_id → id" },
      { from: "regions", to: "clusters", label: "cluster_id → id" },
      { from: "partitions", to: "regions", label: "region_id → id" },
      { from: "accounts", to: "customers", label: "customer_id → id" },
      { from: "wallets", to: "accounts", label: "account_id → id" },
      { from: "transactions", to: "accounts", label: "from_account_id → id" },
      { from: "transactions", to: "accounts", label: "to_account_id → id" },
      { from: "ledger_entries", to: "transactions", label: "transaction_id → id" },
      { from: "ledger_entries", to: "accounts", label: "account_id → id" },
      { from: "settlements", to: "transactions", label: "transaction_id → id" },
      { from: "distributed_locks", to: "nodes", label: "held_by_node → id" },
      { from: "audit_trail", to: "transactions", label: "transaction_id → id" },
      { from: "audit_trail", to: "nodes", label: "node_id → id" },
    ],
  },
};

/**
 * Generates interactive ReactFlow nodes and edges for the specified database engine.
 * Supports custom introspected tables from live database connections, or falls back to
 * the full multi-table domain schema catalog.
 * Dynamically computes an adaptive multi-column grid layout to prevent node overlap.
 */
export function getIntrospectedSchema(
  dbType: string = "PostgreSQL",
  customTables?: TableNodeData[],
  customFks?: { from: string; to: string; label: string }[],
  useFallbackIfEmpty: boolean = false
): DatabaseSchemaResult {
  const schemaDef = ENGINE_SCHEMAS[dbType] || ENGINE_SCHEMAS.PostgreSQL;
  // If customTables is provided (even if empty array []), strictly use it without mock fallback!
  const tables = customTables !== undefined ? customTables : (useFallbackIfEmpty ? schemaDef.tables : []);
  const rawFks = customTables !== undefined ? (customFks || []) : (useFallbackIfEmpty ? schemaDef.fks : []);

  // Calculate dynamic non-overlapping grid layout
  const count = tables.length;
  // Adaptive columns: 4 columns for > 10 tables, 3 for 5-10, 2 for <= 4
  const COLS = count > 10 ? 4 : count > 4 ? 3 : 2;
  const COL_WIDTH = 350;
  const ROW_HEIGHT = 300;

  const nodes: Node<TableNodeData>[] = tables.map((t, index) => {
    const col = index % COLS;
    const row = Math.floor(index / COLS);
    return {
      id: t.tableName,
      type: "tableNode",
      position: {
        x: 40 + col * COL_WIDTH,
        y: 40 + row * ROW_HEIGHT,
      },
      data: t,
    };
  });

  // Build animated edges for relational foreign keys
  const edges: Edge[] = (rawFks || [])
    .filter((fk) => tables.some((t) => t.tableName === fk.from) && tables.some((t) => t.tableName === fk.to))
    .map((fk, idx) => ({
      id: `edge-${fk.from}-${fk.to}-${idx}`,
      source: fk.from,
      target: fk.to,
      animated: true,
      style: { stroke: "#38bdf8", strokeWidth: 1.75 },
      label: fk.label,
      labelStyle: { fill: "#94a3b8", fontSize: 10, fontFamily: "monospace" },
      labelBgStyle: { fill: "#131317", fillOpacity: 0.85, stroke: "#26262b", strokeWidth: 1 },
      labelBgPadding: [6, 3] as [number, number],
      labelBgBorderRadius: 6,
    }));

  return {
    nodes,
    edges,
    tablesCount: nodes.length,
    fksCount: edges.length,
  };
}
